apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    url: http://clickhouse-server:8123
    jsonData:
      defaultDatabase: aura_gold
      server: clickhouse-server
      port: 8123
      username: aura
    secureJsonData:
      password: "${CLICKHOUSE_PASSWORD}"

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: superset
    database: sales_data
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
